### PR TITLE
Add a subcommand to make a `.terraform-version` file

### LINKED ISSUE #90: Add a subcommand to make a `.terraform-version` file
It'd be great if I could easily run a single command to create a `.terraform-version` file matching my current configuration. In rbenv, I would do this by `rbenv local 2.4.2`.

### PR DESCRIPTION
**Pull request by yatmsu**
Add a subcommand to make a `.terraform-version` file.
close #90

### CODE REVIEW

**Comment by yatmsu** [comment]
Since `tfenv was written as inspired by rbenv`, I initially expected to have the local option.
However, there was no local option. Users using rbenv will expect to have the local option.
Also, by using the local option, you can replace the currently installed version or validation.

**Comment by genevera** [comment]
Could you please rebase this against master?

**Comment by yatmsu** [comment]
@genevera Please review.

**Comment by Zordrak** [comment]
Resolved by #270

**Pull request closed without merging**
