### PR TITLE
fixing issue when GREP_OPTIONS='--color=always' is set in environment

### PR DESCRIPTION
**Pull request by Constantin07**
This PR solves the issue reported in #83.

### CODE REVIEW

**Comment by Zordrak** [comment]
I'm not sure it's tfenv's responsibility to be prescriptive on the value of such an environment variable. If a user wishes to override the default colouring behaviour of their version of grep, then the user would normally accept the responsibility to reverse that behaviour when invoking code that it might cause failures for.

**Comment by Constantin07** [comment]
@Zordrak You are right but it allows `tfenv` to work fine in both situations when user has `GREP_OPTIONS` env var set in shell for some/other reasons or not. It took me a while to figure out that the root cause was in grep behaviour.
Also it doesn't make the things worse.

**Comment by genevera** [comment]
I disagree @Zordrak - i think it is tfenv's explicit responsibilty to ensure that it gets command output in the format it needs to run. It is a cli switch which doesn't override functionality anywhere else the user might want it while not stipulating that grep return results without colors breaks tfenv.

**Comment by espoelstra** [comment]
Would it make more sense to simply edit the GREP_OPTIONS environment variable within the `tfenv` core script rather than touching every call to `grep`? Something like `GREP_OPTIONS=${GREP_OPTIONS/--color=.*/--color=never}`

**Comment by Zordrak** [comment]
Sorry for extended absence. Decided that perfect and suitable are not the same thing.

If this helps you, this is fine - it should not harm anyone.

Conflicts need resolving. When I'm not on a phone I will deal with the conflicts unless someone beats me to it.

**Comment by Zordrak** [comment]
@Constantin07 thank you for your contribution, but I realise @espoelstra is correct. As soon as I've modified some greps, we now have merge conflicts because this PR is touching so many individual grep calls, and it's just not going to be a good approach

If you can resubmit a PR that uses @espoelstra s recommendation, and also fixes your problem, I will gladly merge it without delay and include it in the new release due soon.

**Pull request closed without merging**
