### PR TITLE
Allow incomplete versions

### PR DESCRIPTION
**Pull request by thetimbecker**
If min-required doesn't have minor and/or patch version, add them

### CODE REVIEW

**Comment by TheTimBecker** [comment]
I agree that in that case the `latest` keyword is better to use, but this is for the `min-required` feature which intuitively should get the minimum required version. If there is no patch version, the minimum required version can only be assumed to be the earliest available.

It is at least better than the current result, which is the command failing.

The use case I wrote this for was in our CI/CD environment. The pipeline would first install the minimum required version then check the remote state to see what version was used last, and use that version.

Since terraform now supports leaving the patch version off of the required terraform version, I think this tool should support that too.

**Comment by Zordrak** [comment]
It's kinda nasty.. and I think the use of min-required without a patch version is an anti-pattern waiting to bite people; but you make a good point about supporting it.

**Comment by Zordrak** [comment]
Could you throw in a couple of tests for min-required where only 0 or 0.12 are specified?

**Comment by smiller171** [comment]
additionally if you're saying `0.12` you can't use `latest` as that would give you `0.13.2`

**Comment by TheTimBecker** [comment]
@Zordrak I missed you comments earlier, but the most recent comment brought this back to my attention. I am unfamiliar with the testing strategy here, are these 2 tests I added what you were looking for?

I don't know if `0` is a valid value for terraform versions, but I can't imagine why someone would put that. I suppose there _could_ be a valid use case when (or if) terraform version 1.0.0 comes out, but I think we can cross that bridge when it comes.

**Review by Zordrak — APPROVED** [review]

**Review by Zordrak — APPROVED** [review]

**Review by Zordrak — APPROVED** [review]

**Comment by thetimbecker** [comment]
Thank you, this has been on my todo list for a while and I keep ignoring it 😅

**Pull request merged**
