### PR TITLE
Encourage mktemp to respect `TMPDIR`

### PR DESCRIPTION
**Pull request by pentaphobe**
Add the `-t` argument (to `mktemp`) which prepends the `TMPDIR` environment variable if it exists, rather than assuming the current directory is writable

**Jenkins status:**

This currently passes all the same builds as `tfutils/tfenv master`, namely:

- [x] windows
- [x] linux: bionic, xenial, trusty
- osx
   - [x] xcode11.4
   - [x] xcode11.2
   - [x] xcode10.3
   - [x] xcode9.4

Fixes tfutils/tfenv#199

### CODE REVIEW

**Comment by anthraxx** [comment]
`-t` is deprecated, instead it is recommended to use `-p` or `--tmpdir` without an argument to automatically fall back to `$TMPDIR` or `/tmp`.

After replacing `-t` with `-p`, can we get this issue resolved? @Zordrak

**Comment by pentaphobe** [comment]
@anthraxx sorry, misread your comment originally as being actionable by someone else.

> -t is deprecated, instead it is recommended to use -p or --tmpdir without an argument to automatically fall back to $TMPDIR or /tmp.

In which OS is it deprecated?

Neither `-p` nor `--tmpdir` are present in my (MacOS `10.13.6` / Darwin `17.7.0`) installation

Guessing it's either: 
1. only deprecated for _non-Darwin_ systems, or 
2. also deprecated in newer Darwin versions (I can't check this)

If it's the former, then I can easily add an OS check - if it's the latter then someone with a newer system would have to confirm availability of the newer flags

Either way happy to do the leg work, just don't want to inadvertently break the tool for anyone

**Comment by Zordrak** [comment]
I'm open to suggestions. I have tried hard to avoid explicit OS checks just because Mac is always special, and instead solve problems with options that are universally supported. If an OS check is the only way to implement this, then we can do that. But we need to not break support for either in introducing this.

**Comment by pentaphobe** [comment]
Finally got a chance to give it another look - apologies for the duplicate commits (rebased from upstream)

I've reused the same OS detection which is present elsewhere in the same (`tfenv_install`) script for consistency.

Was briefly tempted to set it to a variable given it occurs in more than one place, but didn't want to presume and modify more lines than promised.

Just give a yell if there's anything fishy and I'll update

**Review by Zordrak — APPROVED** [review]

**Pull request merged**
