### PR TITLE
Sorts Remote List

### PR DESCRIPTION
**Pull request by turingbeing**
This PR Sorts the Remote Lists, Displaying newest version at the bottom.

Resolves: https://github.com/tfutils/tfenv/issues/271

### CODE REVIEW

**Comment by turingbeing** [comment]
@Zordrak Requesting Review as can't do it from the actual issue :+1:

**Review by Zordrak — DISMISSED** [review]

**Comment by turingbeing** [comment]
@Zordrak Looks like the tests will need updated since the list is now flipped, I will push new tests also, sorry never thought about that at the the time :+1:

**Comment by Zordrak** [comment]
I will push a new release soon having gone through all outstanding PRs today, but will hold off til you've looked at this,

**Comment by Zordrak** [comment]
Also please take care not only for the presentation of results, but also the logic that parses them where perhaps the first one found may be returned.

**Comment by turingbeing** [comment]
@Zordrak All tests are passing now:

https://github.com/turingbeing/tfenv/actions/runs/1136752141

I will just revert my workflow updates

**Comment by turingbeing** [comment]
I also added a compatible command for OSX since it doesn't have TAC by default :+1:

**Comment by turingbeing** [comment]
@Zordrak Is there anything else you need? Just needs your approval to run the workflow 👍

**Comment by Sickafant** [comment]
Hi,

Thanks for the PR. It would be nice to have this change, but for an additional reason. As per comment https://github.com/tfutils/tfenv/pull/278#issuecomment-898975950

I haven't taken a look at the PR changes yet to see if that is addressed.

The importance is so that it works for custom proxy remotes, like Artifactory. It would be important for tfenv to sort and parse the correct version to use, otherwise you may see bugs like this example:

```
# tfenv list-remote
0.11.15
0.12.24
0.12.28
0.12.30
0.12.31
0.13.6
0.13.7
0.14.11
0.14.7
0.15.1
0.15.5
1.0.11
1.0.3
1.0.4
1.0.8
1.1.6
# tfenv install latest
Terraform v0.11.15 is already installed          # Incorrect, should be 1.1.6
# tfenv install latest:^1
Terraform v1.0.11 is already installed            # Incorrect, should be 1.1.6
# tfenv install latest:^0.12
Terraform v0.12.24 is already installed        # Incorrect, should be 0.12.31
```

Seen on tfenv 2.2.3

**Comment by Zordrak** [comment]
I've been looking at this today and trying to work out what to do for the best.

Bottom line, there's no real justification to choose ASC or DESC ordering; they both achieve the same result; and if something is calling tfenv and wants the inverse it can invert it. At the moment we are presenting and parsing the list in the order we get it from hashicorp, which is DESC by release date.

That said, the justification for handling a custom remote is very important. If it is possible for another remote to providee an improper ordering then it is appropriate for us to order the list.

Unfortunately, we cannot sort the list reliably because we depend then on the lexical ordering of the versions to be consistent, which it isnt, see `1.2.0-alpha20220413` vs. `1.2.0-alpha-20220328`.

Without a guarantee of release-order-consistency in the version names, we can only trust the remote to provide us the release-order, whether ASC or DESC.

What I think this means for solving the remotes problem is that it would be prudent to add an overridable variable to revert the list order from the remote when it is necessary to do so.

However, I think it also is logical to then accept the Hashicorp ordering as the default expectation, and to revert the list only when required by a non-standard repo.

**Comment by Zordrak** [comment]
See https://github.com/tfutils/tfenv/pull/342

**Pull request closed without merging**
