### PR TITLE
Support customizing the config directory via environment variable

### LINKED ISSUE #66: Please make the terraform install location configurable
As homebrew installs new versions of tfenv and cleans up the old versions, all existing terraform installations created by tfenv get deleted because they were installed under tfenv itself. https://github.com/Homebrew/homebrew-core/issues/16077#issuecomment-322051639

### PR DESCRIPTION
**Pull request by e-nomem**
This PR adds `TFENV_CONFIG_DIR` as an environment variable that can be customized. The `use-gnupg`, `use-gpgv`, and `version` files will all live under this directory, as will the `versions` directory where terraform binaries are installed.

This should close #66, which is caused by the fact that all those files and directories currently live under `TFENV_ROOT`, which can get blown away by a homebrew upgrade.

It incidentally also fixes a general issue where `tfenv` is globally installed on a system in a location where all users do not have write permissions, preventing them from installing user-specific versions of terraform.

### CODE REVIEW

**Comment by Zordrak** [comment]
Apologies, I'm trying to work through the PR backlog. the v2.0.0 release has done significant damage to this PR, so will need time to look at how to fix it up and then assess the impact of the change

**Comment by e-nomem** [comment]
@Zordrak let me know if you have any issues with the way this feature is currently implemented in general, and I'll take some time in the next few days to rebase the PR and address the feedback at the same time.

**Comment by Zordrak** [comment]
Seems reasonable in concept

**Comment by e-nomem** [comment]
Ok, I've fixed up the PR on the master branch

**Comment by anthraxx** [comment]
data like terraform installation does not belong into `XDG_CONFIG_HOME` that's purely meant to contain configuration. That's what `XDG_DATA_HOME` is for, containing application data beyond pure configuration.

**Review by Zordrak — APPROVED** [review]

**Comment by bouk** [comment]
@Zordrak could you cut a release with this addition? 🙂

**Pull request merged**
